[paths]
piezo_audio_path = "data/NB_Ch3.flac"
#amb_audio_path = "data/Bl122_amb_short.flac"
#label_path = "data/Bl122_piezo_short.txt"

[parameters]
rms_threshold = 5
hilbert_smooth = 5
hilbert_threshold = 10
minimum_distance = 30
minimum_length = 90

[spec]
write_img = false
write_dir = ""